theme: fullwidth
abstract: Documentation/*.md
custom_categories:

  # Pricing API

  - name: Pricing API
    children:
      - PricingAPI
      - PricingAPIOperation

  - name: Postage Options
    children:
      - PostageOptionsRequest
      - PostageOptionsAnswer

  - name: Zone Offers
    children:
      - ZoneOffersRequest
      - ZoneOffersAnswer

  - name: Print Type
    children:
      - PrintTypeRequest
      - PrintTypeAnswer

  - name: Paper Type
    children:
      - PaperTypeRequest
      - PaperTypeAnswer

  - name: Envelopes Available
    children:
      - EnvelopesAvailableRequest
      - EnvelopesAvailableAnswer

  # Letter API

  - name: Letter API
    children:
      - LetterAPI
      - LetterAPIOperation

  - name: Submit Letter
    children:
      - SubmitLetterForPostingRequest
      - SubmitLetterForPostingRequestBody
      - SubmitLetterForPostingAnswer

  - name: Upload Document
    children:
      - UploadDocumentRequest
      - UploadDocumentRequestBody
      - UploadDocumentAnswer

  # Countries

  - name: Countries List
    children:
      - CountriesList
      - CountriesAnswer
