theme: fullwidth
abstract: Documentation/*.md
custom_categories:
  - name: Postage Options
    children:
      - ZonesLetterCanBeSentFromRequest
      - ZonesLetterCanBeSentFromAnswer

  - name: Zone Offers
    children:
      - ZoneOffersRequest
      - ZoneOffersAnswer

  - name: Submit Letter
    children:
      - SubmitLetterForPostingRequest
      - SubmitLetterForPostingRequestBody
      - SubmitLetterForPostingAnswer

  - name: Upload Document
    children:
      - UploadDocumentRequest
      - UploadDocumentRequestBody
      - UploadDocumentAnswer
